using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class Ending : MonoBehaviour
{
    #region//publicï¿½Ïï¿½
    [Header("Characterï¿½Ìƒvï¿½ï¿½ï¿½nï¿½u")] public GameObject character;
    public GameObject canvas;
    [Header("ï¿½eï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½X")] public float[] characterStatus = new float[15];
    [Header("ï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½ÌÅ‘ï¿½l")] public float maxStatus; //ï¿½Xï¿½eï¿½[ï¿½^ï¿½Xï¿½ï¿½ï¿½ï¿½l
    [Header("ï¿½ï¿½ï¿½ï¿½Sprite")] public Sprite[] star = new Sprite[5];
    [Header("ï¿½Aï¿½Nï¿½eï¿½Bï¿½uï¿½Xï¿½Lï¿½ï¿½ï¿½Qï¿½[ï¿½Wï¿½ï¿½Sprite")] public Sprite[] activeSkillGaugeSprites = new Sprite[6];
    [Header("ï¿½pï¿½bï¿½Vï¿½uï¿½Xï¿½Lï¿½ï¿½ï¿½Qï¿½[ï¿½Wï¿½ï¿½Sprite")] public Sprite[] passiveSkillGaugeSprites = new Sprite[6];
    [Header("ï¿½ï¿½ï¿½Ìï¿½")] public int maxStar; //ï¿½ï¿½ï¿½Ìï¿½
    public ProgressModel[] Characters = new ProgressModel[5];
    #endregion

    #region//privateï¿½Ïï¿½
    private int currentCharacterNumber = 0;
    private int currentCharacterVocal = 0;
    private int currentCharacterVisual = 0;
    private int currentCharacterDance = 0;
    private GameObject Star = null;
    private Image activeSkillGaugeImage = null;
    private Image passiveSkillGaugeImage = null;
    private List<Image> VocalStarImage = new List<Image>();
    private List<Image> VisualStarImage = new List<Image>();
    private List<Image> DanceStarImage = new List<Image>();
    private List<GameObject> CharacterList = new List<GameObject>();
    private List<GameObject> CharacterButtonList = new List<GameObject>();
    #endregion

    void Start()
    {
        FindStar();
        FindButton();
        FindGauge();
        CharacterButtonList[0].transform.localScale = new Vector3(1.8f, 1.8f, 1.8f);
        CharacterButtonList[0].GetComponent<Image>().color = new Color(1.0f, 1.0f, 1.0f, 1.0f);
        SetCharacter();
        ChangeCurrentCharacterStars(0);
        ChangeCurrentCharacterSKillGauge(0);
    }

    /// <summary>
    /// ï¿½\ï¿½ï¿½ï¿½ï¿½Ê‚ï¿½iï¿½Ô–Ú‚ÌƒLï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÉØ‚ï¿½Ö‚ï¿½
    /// </summary>
    /// <param name="i"></param>
    public void ChangeCurrentCharacter(int i)
    {
#if UNITY_EDITOR
        //Debug.Log(i);
#endif
        if (currentCharacterNumber != i)
        {
            CharacterList[currentCharacterNumber].GetComponent<Image>().enabled = false;
            CharacterButtonList[currentCharacterNumber].transform.localScale = new Vector3(1.5f, 1.5f, 1.5f);
            CharacterButtonList[currentCharacterNumber].GetComponent<Image>().color = new Color(110.0f / 255.0f, 110.0f / 255.0f, 110.0f / 255.0f, 1.0f);
            CharacterButtonList[i].transform.localScale = new Vector3(1.8f, 1.8f, 1.8f);
            CharacterButtonList[i].GetComponent<Image>().color = new Color(1.0f, 1.0f, 1.0f, 1.0f);
            ChangeCurrentCharacterImage(i);
            ChangeCurrentCharacterStars(i);
            ChangeCurrentCharacterSKillGauge(i);
            currentCharacterNumber = i;
        }
    }

    /// <summary>
    /// iï¿½Ô–Ú‚ÌƒLï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½É—ï¿½ï¿½ï¿½ï¿½Gï¿½ï¿½ÏX
    /// </summary>
    /// <param name="i"></param>
    private void ChangeCurrentCharacterImage(int i)
    {
        CharacterList[i].GetComponent<Image>().enabled = true;
    }

    /// <summary>
    /// iï¿½Ô–Ú‚ÌƒLï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½Éï¿½ï¿½í‚¹ï¿½Äï¿½ï¿½Ìï¿½ï¿½ï¿½ÏX
    /// </summary>
    /// <param name="i"></param>
    private void ChangeCurrentCharacterStars(int i)
    {
        //ï¿½eï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½ï¿½Ç‚İï¿½ï¿½İAï¿½Xï¿½eï¿½[ï¿½^ï¿½Xï¿½ÌÅ‘ï¿½lï¿½ğ’´‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½ê‡ï¿½Í‚ï¿½ï¿½Ì’lï¿½ï¿½ï¿½Xï¿½eï¿½[ï¿½^ï¿½Xï¿½ÌÅ‘ï¿½lï¿½É•ÏX
        currentCharacterVocal = (int)Mathf.Min(Common.progresses[i].Vocal, maxStatus);
        currentCharacterVisual = (int)Mathf.Min(Common.progresses[i].Visual, maxStatus);
        currentCharacterDance = (int)Mathf.Min(Common.progresses[i].Dance, maxStatus);

        currentCharacterVocal = (int)(((float)currentCharacterVocal / (float)maxStatus) * 50.0f);
        currentCharacterVisual = (int)(((float)currentCharacterVisual / (float)maxStatus) * 50.0f);
        currentCharacterDance = (int)(((float)currentCharacterDance / (float)maxStatus) * 50.0f);

        SetSongStar(currentCharacterVocal);
        SetVisualStar(currentCharacterVisual);
        SetDanceStar(currentCharacterDance);

    }

    /// <summary>
    /// iï¿½Ô–Ú‚ÌƒLï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½ÌƒXï¿½eï¿½[ï¿½^ï¿½Xï¿½Éï¿½ï¿½í‚¹ï¿½ÄƒXï¿½Lï¿½ï¿½ï¿½Qï¿½[ï¿½Wï¿½ï¿½ÏX
    /// </summary>
    /// <param name="i"></param>
    private void ChangeCurrentCharacterSKillGauge(int i)
    {
        activeSkillGaugeImage.sprite = activeSkillGaugeSprites[Common.progresses[i].ActiveSkillLevel];
        passiveSkillGaugeImage.sprite = passiveSkillGaugeSprites[Common.progresses[i].PassiveSkillLevel];
    }

    /// <summary>
    /// ï¿½eSongStarï¿½ï¿½Spriteï¿½ï¿½^ï¿½ï¿½ï¿½ï¿½ê‚½statusï¿½Éï¿½ï¿½í‚¹ï¿½Ä•ÏX
    /// </summary>
    /// <param name="status"></param>
    private void SetSongStar(int status)
    {
#if UNITY_EDITOR
        //Debug.Log("Vocal" + status);
#endif
        for (int i = 0; i < status / 5; i++)
        {
            VocalStarImage[i].enabled = true;
            VocalStarImage[i].sprite = star[4];
        }
        if (status != 50)
        {
            if (status % 5 == 0)
            {
                VocalStarImage[status / 5].enabled = false;
            }
            else
            {
                VocalStarImage[status / 5].enabled = true;
                VocalStarImage[status / 5].sprite = star[(status % 5) - 1];
            }
        }
        for (int i = status / 5 + 1; i < maxStar; i++)
        {
            VocalStarImage[i].enabled = false;
        }
    }

    /// <summary>
    /// ï¿½eVisualStarï¿½ï¿½Spriteï¿½ï¿½^ï¿½ï¿½ï¿½ï¿½ê‚½statusï¿½Éï¿½ï¿½í‚¹ï¿½Ä•ÏX
    /// </summary>
    /// <param name="status"></param>
    private void SetVisualStar(int status)
    {
#if UNITY_EDITOR
        //Debug.Log("Visual" + status);
#endif
        for (int i = 0; i < status / 5; i++)
        {
            VisualStarImage[i].enabled = true;
            VisualStarImage[i].sprite = star[4];
        }
        if (status != 50)
        {
            if (status % 5 == 0)
            {
                VisualStarImage[status / 5].enabled = false;
            }
            else
            {
                VisualStarImage[status / 5].enabled = true;
                VisualStarImage[status / 5].sprite = star[(status % 5) - 1];
            }
        }
        for (int i = status / 5 + 1; i < maxStar; i++)
        {
            VisualStarImage[i].enabled = false;
        }
    }

    /// <summary>
    /// ï¿½eDanceStarï¿½ï¿½Spriteï¿½ï¿½^ï¿½ï¿½ï¿½ï¿½ê‚½statusï¿½Éï¿½ï¿½í‚¹ï¿½Ä•ÏX
    /// </summary>
    /// <param name="status"></param>
    private void SetDanceStar(int status)
    {
#if UNITY_EDITOR
        //Debug.Log("Dance" + status);
#endif
        for (int i = 0; i < status / 5; i++)
        {
            DanceStarImage[i].enabled = true;
            DanceStarImage[i].sprite = star[4];
        }
        if (status != 50)
        {
            if (status % 5 == 0)
            {
                DanceStarImage[status / 5].enabled = false;
            }
            else
            {
                DanceStarImage[status / 5].enabled = true;
                DanceStarImage[status / 5].sprite = star[(status % 5) - 1];
            }
        }
        for (int i = status / 5 + 1; i < maxStar; i++)
        {
            DanceStarImage[i].enabled = false;
        }
    }

    /// <summary>
    /// ï¿½eStarï¿½ï¿½Imageï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½ï¿½ß‚Ü‚ï¿½ï¿½ï¿½
    /// </summary>
    private void FindStar()
    {
        for (int i = 1; i <= maxStar; i++)
        {
            Star = GameObject.Find("VocalStar" + i);
            VocalStarImage.Add(Star.GetComponent<Image>());
            Star = GameObject.Find("VisualStar" + i);
            VisualStarImage.Add(Star.GetComponent<Image>());
            Star = GameObject.Find("DanceStar" + i);
            DanceStarImage.Add(Star.GetComponent<Image>());
        }
    }

    /// <summary>
    /// ï¿½eButtonï¿½ï¿½ß‚Ü‚ï¿½ï¿½ï¿½
    /// </summary>
    private void FindButton()
    {
        for (int i = 1; i <= 5; i++)
        {
            CharacterButtonList.Add(GameObject.Find("CharacterButton" + i));
        }
    }

    /// <summary>
    /// ï¿½eGaugeï¿½ï¿½ß‚Ü‚ï¿½ï¿½ï¿½
    /// </summary>
    private void FindGauge()
    {
        activeSkillGaugeImage = GameObject.Find("ActiveSkillGauge").GetComponent<Image>();
        passiveSkillGaugeImage = GameObject.Find("PassiveSkillGauge").GetComponent<Image>();
    }

    /// <summary>
    /// ï¿½ï¿½ï¿½ê‚¼ï¿½ï¿½ÌƒLï¿½ï¿½ï¿½ï¿½ï¿½Nï¿½^ï¿½[ï¿½æ‘œï¿½ï¿½MainCharacterIDï¿½ï¿½ï¿½ï¿½æ“¾
    /// </summary>
    private void SetCharacter()
    {
        var parent = canvas.transform;
        for (int i = 0; i < 5; i++)
        {
            GameObject C = Instantiate(character, parent);
            CharacterList.Add(C);
            CharacterList[i].GetComponent<RectTransform>().anchoredPosition = new Vector2(0, 0);
            CharacterList[i].GetComponent<Image>().sprite = Resources.Load<Sprite>("Images/standimage/" + Common.progresses[i].MainCharacterId);
            CharacterButtonList[i].GetComponent<Image>().sprite = Resources.Load<Sprite>("Images/Live/Gif/" + Common.progresses[i].MainCharacterId + "/Ch-0");
            CharacterList[i].GetComponent<Image>().enabled = false;
            if (i == 0) CharacterList[i].GetComponent<Image>().enabled = true;
        }
    }

    public void ResetStory()
    {
        Common.subseplayer.PlayOneShot(Common.seclips["ok1"]);
        Common.loadingCanvas.SetActive(true);
        Common.loadingGif.GetComponent<GifPlayer>().index = 0;
        Common.loadingGif.GetComponent<GifPlayer>().StartGif();
        Common.bgmplayer.Stop();
        Common.bgmplayer.time = 0;
        Common.mainstoryid = null;
        ProgressService.FetchStory();
        ProgressService.FetchCompletedProgressAndUpdateGameStatus("home");
    }

    bool triggerdPlayer = false;
    void Update()
    {
        if (!triggerdPlayer && SceneManager.GetActiveScene().name == "Ending")
        {
            Common.bgmplayer.clip = (AudioClip)Resources.Load("Music/BG09");
            Common.bgmplayer.Play();
            triggerdPlayer = true;
        }
    }
}
